
// GRAY
var TritonTheme = {
    BACKGROUND_COLOR : '#1f1f1f',
    TEXT_COLOR : '#aaaaaa',
    BORDER_COLOR : '#aaaaaa',

    POPUP_BACKGROUND_COLOR : '#1f1f1f',
    POPUP_TEXT_COLOR : '#aaaaaa',
    POPUP_TITLE_BACKGROUND_COLOR : '#343434',
    POPUP_TITLE_TEXT_COLOR : '#FFFFFF',
    POPUP_CLOSE_BUTTON_IMAGE_URL : '/res/lia/triton/img/img_alert_popup_close_gray.png',
    POPUP_CONFIRM_BUTTON_BORDER_COLOR : '#aaaaaa',
    POPUP_CONFIRM_BUTTON_HOVERING_BORDER_COLOR : '#ffffff',
    POPUP_CONFIRM_BUTTON_TEXT_COLOR : '#aaaaaa',
    POPUP_CONFIRM_BUTTON_HOVERING_TEXT_COLOR : '#ffffff',
    POPUP_CONFIRM_BUTTON_BACKGROUND_COLOR : '#1f1f1f',
    POPUP_CONFIRM_BUTTON_HOVERING_BACKGROUND_COLOR : '#666666',
    POPUP_CANCEL_BUTTON_BORDER_COLOR : '#aaaaaa',
    POPUP_CANCEL_BUTTON_HOVERING_BORDER_COLOR : '#ffffff',
    POPUP_CANCEL_BUTTON_TEXT_COLOR : '#aaaaaa',
    POPUP_CANCEL_BUTTON_HOVERING_TEXT_COLOR : '#ffffff',
    POPUP_CANCEL_BUTTON_BACKGROUND_COLOR : '#1f1f1f',
    POPUP_CANCEL_BUTTON_HOVERING_BACKGROUND_COLOR : '#666666',

    LIST_TABLE_BORDER_COLOR : '#414141',
    LIST_TABLE_TEXT_COLOR : '#aaaaaa',
    LIST_TABLE_BACKGROUND_COLOR : '#1f1f1f',
    LIST_TABLE_HOVERING_TEXT_COLOR : '#ffffff',
    LIST_TABLE_HOVERING_BACKGROUND_COLOR : '#666666',
    LIST_TABLE_HEADER_BACKGROUND_COLOR : '#191919',
    LIST_TABLE_HEADER_TEXT_COLOR : '#e1e1e1',
    // 색상 설정 해야함
    LIST_TABLE_HIGH_TEXT_COLOR : '#5d5d5d',
    LIST_TABLE_HIGH_BACKGROUND_COLOR : '#edf7fe',
    LIST_TABLE_ALWAYS_ON_TOP_TEXT_COLOR : '#5d5d5d',
    LIST_TABLE_ALWAYS_ON_TOP_BACKGROUND_COLOR : 'rgb(248, 248, 248)',
    LIST_TABLE_ALWAYS_ON_TOP_HOVERING_TEXT_COLOR : '#084897',
    LIST_TABLE_SELECTED_TEXT_COLOR : '#084897',
    LIST_TABLE_SELECTED_BACKGROUND_COLOR : '#f7f7f7',
    LIST_TABLE_DIVISION_TEXT_COLOR : '#084897',
    LIST_TABLE_DIVISION_BACKGROUND_COLOR : '#f7f7f7',

    DETAIL_TABLE_BORDER_COLOR : '#414141',
    DETAIL_TABLE_BACKGROUND_COLOR : '#1f1f1f',
    DETAIL_TABLE_TEXT_COLOR : '#aaaaaa',
    DETAIL_TABLE_POINT_BACKGROUND_COLOR : '#191919',
    DETAIL_TABLE_POINT_TEXT_COLOR : '#ffffff',

    PANEL_BORDER_COLOR : '#e1e1e1',

    TITLE_POINT_COLOR : '#666666',
    TITLE_TEXT_COLOR : '#ffffff',

    SUB_TITLE_TEXT_COLOR : '#ffffff',

    HEADER_MENU_BUTTON_DEFAULT_FONT_COLOR : '#7a7a7a',
    HEADER_MENU_BUTTON_HOVERING_FONT_COLOR : '#606060',
    HEADER_MENU_BUTTON_PRESSED_FONT_COLOR : '#253a73',
    HEADER_MENU_BUTTON_INVERSE_FONT_COLOR : '#ffffff',

    TOP_DROP_DOWN_MENU_STATUS_BACKGROUND_COLOR: '#e8e8e8',
    TOP_DROP_DOWN_MENU_STATUS_CLOCK_BACKGROUND_COLOR: '#606060',
    TOP_DROP_DOWN_MENU_STATUS_CLOCK_COLOR: '#ffffff',

    TOP_DROP_DOWN_MENU_BORDER_COLOR : '#414141',
    TOP_DROP_DOWN_MENU_TAB_CONTAINER_BACKGROUND_COLOR : '#343434',
    TOP_DROP_DOWN_MENU_PANEL_BORDER_COLOR : '#414141',
    TOP_DROP_DOWN_MENU_TEXT_COLOR : '#ffffff',
    TOP_DROP_DOWN_MENU_ALARM_SUB_TITLE_TEXT_COLOR : '#999999',
    TOP_DROP_DOWN_MENU_TAB_BACKGROUND_COLOR : '#2a2a2a',
    TOP_DROP_DOWN_MENU_TAB_SELECTED_BACKGROUND_COLOR : '#1f1f1f',
    TOP_DROP_DOWN_MENU_TAB_BORDER_COLOR : '#424242',
    TOP_DROP_DOWN_MENU_MENU_ITEM_SELECTED_BACKGROUND_COLOR : '#474747',
    TOP_DROP_DOWN_MENU_QUICK_MENU_ITEM_SELECTED_BACKGROUND_COLOR : '#474747',
    TOP_DROP_DOWN_MENU_ALARM_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_notice.png',
    TOP_DROP_DOWN_MENU_ALARM_POINT_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_notice_point.png',
    TOP_DROP_DOWN_MENU_QUICK_MENU_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_quickmenu.png',
    TOP_DROP_DOWN_MENU_MENU_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_menu.png',
    TOP_DROP_DOWN_MENU_ICON_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_menu_icon.png',
    TOP_DROP_DOWN_MENU_BACK_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_back.png',
    TOP_DROP_DOWN_MENU_MENU_MORE_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_header_more.png',
    TOP_DROP_DOWN_MENU_ARROW_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/img_arrow.png',
    TOP_DROP_DOWN_MENU_TAB_CLOSE_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_tabclose.png', // pressed 이미지 추가해야함
    TOP_DROP_DOWN_MENU_MOBILE_1DEPTH_DOWN_ARROW_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/arr_menu_1depth_down.png',
    TOP_DROP_DOWN_MENU_1DEPTH_DOWN_ARROW_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_arr_menu.png',
    TOP_DROP_DOWN_MENU_1DEPTH_DOWN_ARROW_SELECTED_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_arr_menu_pressed.png',
    TOP_DROP_DOWN_MENU_TAB_LEFT_ARROW_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_tabarr_left.png',
    TOP_DROP_DOWN_MENU_TAB_RIGHT_ARROW_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown_gray/btn_tabarr_right.png',

    SIDE_DROP_DOWN_MENU_PANEL_WIDTH_DEFAULT : '220px',
    SIDE_DROP_DOWN_MENU_STATUS_CLOCK_COLOR: '#ffffff',
    SIDE_DROP_DOWN_MENU_PANEL_BACKGROUND_COLOR: '#ffffff',
    SIDE_DROP_DOWN_MENU_PANEL_LINE_COLOR: 'rgb(230, 230, 230)',
    SIDE_DROP_DOWN_MENU_PANEL_DEPTH_2_BACKGROUND_COLOR: '#f2f6fa',
    SIDE_DROP_DOWN_MENU_PANEL_DEPTH_3_BACKGROUND_COLOR: '#ffffff',
    SIDE_DROP_DOWN_MENU_PANEL_DEPTH_4_BACKGROUND_COLOR: 'rgba(242, 246, 250, 0.8)',
    SIDE_DROP_DOWN_MENU_PANEL_TEXT_COLOR: '#696969',
    SIDE_DROP_DOWN_MENU_PANEL_SELECTED_BACKGROUND_COLOR: '#003679',
    SIDE_DROP_DOWN_MENU_PANEL_DEPTH_1_SELECTED_TEXT_COLOR: '#ffffff',
    SIDE_DROP_DOWN_MENU_PANEL_SELECTED_TEXT_COLOR: '#003679',
    SIDE_DROP_DOWN_MENU_MENU_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/btn_menu.png',
    SIDE_DROP_DOWN_MENU_PANEL_2_DOWN_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/btn_menu_more.png',
    SIDE_DROP_DOWN_MENU_PANEL_2_DOWN_ARROW_SELECTED_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/btn_menu_more_pressed.png',
    SIDE_DROP_DOWN_MENU_PANEL_3_DOWN_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/btn_menu_more.png',
    SIDE_DROP_DOWN_MENU_PANEL_3_DOWN_ARROW_SELECTED_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/btn_menu_more_pressed.png',

    // SIDE_DROP_DOWN_MENU_PANEL_WIDTH_DEFAULT : '220px',
    // SIDE_DROP_DOWN_MENU_STATUS_CLOCK_COLOR: '#ffffff',
    // SIDE_DROP_DOWN_MENU_PANEL_LINE_COLOR: '#333333',
    // SIDE_DROP_DOWN_MENU_PANEL_BACKGROUND_COLOR: '#333333',
    // SIDE_DROP_DOWN_MENU_PANEL_DEPTH_2_BACKGROUND_COLOR: '#2c2b2b',
    // SIDE_DROP_DOWN_MENU_PANEL_DEPTH_3_BACKGROUND_COLOR: '#222222',
    // SIDE_DROP_DOWN_MENU_PANEL_TEXT_COLOR: '#aaaaaa',
    // SIDE_DROP_DOWN_MENU_PANEL_SELECTED_BACKGROUND_COLOR: '#222222',
    // SIDE_DROP_DOWN_MENU_PANEL_DEPTH_1_SELECTED_TEXT_COLOR: '#ffffff',
    // SIDE_DROP_DOWN_MENU_PANEL_SELECTED_TEXT_COLOR: '#ffffff',
    // SIDE_DROP_DOWN_MENU_MENU_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown_gray/btn_menu.png',
    // SIDE_DROP_DOWN_MENU_PANEL_2_DOWN_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown_gray/btn_menu_more.png',
    // SIDE_DROP_DOWN_MENU_PANEL_2_DOWN_ARROW_SELECTED_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown_gray/btn_menu_more_pressed.png',

    SIDE_DROP_DOWN_MENU_STATUS_BACKGROUND_COLOR: '#e8e8e8',
    SIDE_DROP_DOWN_MENU_STATUS_CLOCK_BACKGROUND_COLOR: '#606060',
    SIDE_DROP_DOWN_MENU_PANEL_1_DOWN_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/arr_menu_down.png',
    SIDE_DROP_DOWN_MENU_PANEL_1_DOWN_ARROW_SELECTED_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/arr_menu_up.png',
    SIDE_DROP_DOWN_MENU_MOBILE_1DEPTH_DOWN_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_sidedropdown/arr_menu_1depth_down.png',
    SIDE_DROP_DOWN_MENU_TEXT_COLOR: '#000000',
    SIDE_DROP_DOWN_MENU_BORDER_COLOR: '#e6e6e6',
    SIDE_DROP_DOWN_MENU_TAB_CONTAINER_BACKGROUND_COLOR: '#e6e6e6',
    SIDE_DROP_DOWN_MENU_PANEL_BORDER_COLOR: '#cecece',
    SIDE_DROP_DOWN_MENU_ALARM_SUB_TITLE_TEXT_COLOR: '#666666',
    SIDE_DROP_DOWN_MENU_TAB_BACKGROUND_COLOR: '#ebebeb',
    SIDE_DROP_DOWN_MENU_TAB_SELECTED_BACKGROUND_COLOR: '#ffffff',
    SIDE_DROP_DOWN_MENU_TAB_BORDER_COLOR: '#d1d1d1',
    SIDE_DROP_DOWN_MENU_QUICK_MENU_ITEM_SELECTED_BACKGROUND_COLOR: '#e9eef6',
    SIDE_DROP_DOWN_MENU_ALARM_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_notice.png',
    SIDE_DROP_DOWN_MENU_ALARM_NOTICE_BACKGROUND_COLOR: '#d85460',
    SIDE_DROP_DOWN_MENU_ALARM_NOTICE_BUTTON_IMAGE_URL : '/res/lia/triton/img/menu_topdropdown/btn_notice_alaram.png',
    SIDE_DROP_DOWN_MENU_ALARM_POINT_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_notice_point.png',
    SIDE_DROP_DOWN_MENU_QUICK_MENU_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_quickmenu.png',
    SIDE_DROP_DOWN_MENU_ICON_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_menu_icon.png',
    SIDE_DROP_DOWN_MENU_BACK_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_back.png',
    SIDE_DROP_DOWN_MENU_MENU_MORE_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_header_more.png',
    SIDE_DROP_DOWN_MENU_ARROW_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/img_arrow.png',
    SIDE_DROP_DOWN_MENU_TAB_CLOSE_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_tabclose.png',
    SIDE_DROP_DOWN_MENU_TAB_LEFT_ARROW_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_tabarr_left.png',
    SIDE_DROP_DOWN_MENU_TAB_RIGHT_ARROW_BUTTON_IMAGE_URL: '/res/lia/triton/img/menu_topdropdown/btn_tabarr_right.png',

    CHECK_BOX_NORMAL_IMAGE_URL : '/res/lia/triton/img/checkbox_gray.png',
    CHECK_BOX_PRESSED_IMAGE_URL : '/res/lia/triton/img/checkbox_gray_pressed.png',
    // 색상 설정 해야함
    CHECK_BOX_INACTIVE_IMAGE_URL : '/res/lia/triton/img/checkbox_gray_inactive.png',
    CHECK_BOX_PRESSED_INACTIVE_IMAGE_URL : '/res/lia/triton/img/checkbox_gray_pressed_inactive.png',
    CHECK_BOX_TOGGLE_IMAGE_URL : '/res/lia/triton/img/toggle_gray.png',
    CHECK_BOX_TOGGLE_PRESSED_IMAGE_URL : '/res/lia/triton/img/toggle_gray_pressed.png',

    SECTION_BORDER : '#414141',

    COMBO_BOX_BACKGROUND_COLOR : '#1f1f1f',
    COMBO_BOX_BORDER_COLOR : '#414141',
    COMBO_BOX_TEXT_COLOR : '#aaaaaa',
    COMBO_BOX_ARROW_COLOR : '#aaaaaa',
    // 색상 설정 해야함
    COMBO_BOX_DISABLED_BACKGROUND_COLOR : 'rgb(235, 235, 228)',
    COMBO_BOX_DISABLED_BORDER_COLOR : '#d7d7d5',
    COMBO_BOX_DISABLED_TEXT_COLOR : '#5d5d5d',
    COMBO_BOX_DISABLED_ARROW_COLOR : '#5d5d5d',
    COMBO_BOX_CATEGORY_BACKGROUND_COLOR : '#1f1f1f',
    COMBO_BOX_CATEGORY_BORDER_COLOR : '#414141',
    COMBO_BOX_CATEGORY_TEXT_COLOR : '#aaaaaa',
    COMBO_BOX_CATEGORY_ARROW_COLOR : '#aaaaaa',
    COMBO_BOX_SUB_MENU_TITLE_BACKGROUND_COLOR : '#1f1f1f',
    COMBO_BOX_SUB_MENU_TITLE_TEXT_COLOR : '#aaaaaa',
    COMBO_BOX_SUB_MENU_TITLE_ARROW_COLOR : '#aaaaaa',

    TEXT_INPUT_BACKGROUND_COLOR : '#1f1f1f',
    TEXT_INPUT_TEXT_COLOR : '#aaaaaa',
    TEXT_INPUT_BORDER_COLOR : '#414141',

    SUB_MENU_TITLE_BACKGROUND : '#474747',
    SUB_MENU_BACKGROUND : '#343434',
    SUB_MENU_TEXT_COLOR : '#ffffff',
    SUB_MENU_BORDER_COLOR : '#414141',
    SUB_MENU_ITEM_BACKGROUND_COLOR : '#343434',
    SUB_MENU_ITEM_TEXT_COLOR : '#aaaaaa',
    SUB_MENU_ITEM_PRESSED_BACKGROUND_COLOR : '#282828',
    SUB_MENU_ITEM_PRESSED_TEXT_COLOR : '#ffffff',
    SUB_MENU_ITEM_SUB_LIST_BACKGROUND : '#343434',
    SUB_MENU_ITEM_SUB_LIST_PRESSED_BACKGROUND : '#282828',
    // 이미지 필요
    SUB_MENU_FLAG_OPEN_IMAGE_URL : '/res/lia/triton/img/img_submenu_open.png',
    SUB_MENU_FLAG_CLOSE_IMAGE_URL : '/res/lia/triton/img/img_submenu_close.png',
    SUB_MENU_MARK_IMAGE_URL : '/res/lia/triton/img/img_submenu_mark.png',

    FLAT_BUTTON_NORMAL_BACKGROUND_COLOR : '#1f1f1f',
    FLAT_BUTTON_NORMAL_HOVER_BACKGROUND_COLOR : '#666666',
    FLAT_BUTTON_NORMAL_TEXT_COLOR : '#aaaaaa',
    FLAT_BUTTON_NORMAL_HOVER_TEXT_COLOR : '#ffffff',
    FLAT_BUTTON_NORMAL_BORDER_COLOR : '#aaaaaa',
    FLAT_BUTTON_NORMAL_HOVER_BORDER_COLOR : '#ffffff',
    // 색상 변경 필요
    FLAT_BUTTON_DELETE_BACKGROUND_COLOR : '#1f1f1f',
    FLAT_BUTTON_DELETE_HOVER_BACKGROUND_COLOR : '#666666',
    FLAT_BUTTON_DELETE_TEXT_COLOR : '#aaaaaa',
    FLAT_BUTTON_DELETE_HOVER_TEXT_COLOR : '#ffffff',
    FLAT_BUTTON_DELETE_BORDER_COLOR : '#aaaaaa',
    FLAT_BUTTON_DELETE_HOVER_BORDER_COLOR : '#ffffff',
    FLAT_BUTTON_SHADE_BACKGROUND_COLOR : '#1f1f1f',
    FLAT_BUTTON_SHADE_HOVER_BACKGROUND_COLOR : '#666666',
    FLAT_BUTTON_SHADE_TEXT_COLOR : '#aaaaaa',
    FLAT_BUTTON_SHADE_HOVER_TEXT_COLOR : '#ffffff',
    FLAT_BUTTON_SHADE_BORDER_COLOR : '#aaaaaa',
    FLAT_BUTTON_SHADE_HOVER_BORDER_COLOR : '#ffffff',
    FLAT_BUTTON_SQUARE_BACKGROUND_COLOR : '#1f1f1f',
    FLAT_BUTTON_SQUARE_HOVER_BACKGROUND_COLOR : '#666666',
    FLAT_BUTTON_SQUARE_TEXT_COLOR : '#aaaaaa',
    FLAT_BUTTON_SQUARE_HOVER_TEXT_COLOR : '#ffffff',
    FLAT_BUTTON_SQUARE_BORDER_COLOR : '#aaaaaa',
    FLAT_BUTTON_SQUARE_HOVER_BORDER_COLOR : '#ffffff',
    FLAT_BUTTON_SEARCH_BACKGROUND_COLOR : '#1f1f1f',
    FLAT_BUTTON_SEARCH_HOVER_BACKGROUND_COLOR : '#666666',
    FLAT_BUTTON_SEARCH_TEXT_COLOR : '#aaaaaa',
    FLAT_BUTTON_SEARCH_HOVER_TEXT_COLOR : '#ffffff',
    FLAT_BUTTON_SEARCH_BORDER_COLOR : '#aaaaaa',
    FLAT_BUTTON_SEARCH_HOVER_BORDER_COLOR : '#ffffff',
    FLAT_BUTTON_SEARCH_ICON_IMAGE_URL : '/res/lia/triton/img/img_search.png',
    FLAT_BUTTON_EXCEL_ICON_IMAGE_URL : '/res/lia/triton/img/img_exceldown.png',
    FLAT_BUTTON_REFRESH_ICON_IMAGE_URL : '/res/lia/triton/img/img_restore.png',
    FLAT_BUTTON_EDIT_SMALL_ICON_IMAGE_URL : '/res/lia/triton/img/img_small_edit.png',
    FLAT_BUTTON_EDIT_SMALL_BLUE_ICON_IMAGE_URL : '/res/lia/triton/img/img_small_edit_blue.png',
    FLAT_BUTTON_INQUIRY_SMALL_ICON_IMAGE_URL : '/res/lia/triton/img/img_small_list_view.png',
    FLAT_BUTTON_DELETE_SMALL_ICON_IMAGE_URL : '/res/lia/triton/img/img_small_x_red.png',
    FLAT_BUTTON_DELETE_SMALL_GRAY_ICON_IMAGE_URL : '/res/lia/triton/img/img_small_x_gray.png',

    DATETIME_PICKER_BORDER_COLOR : '#414141',
    DATETIME_PICKER_BACKGROUND_COLOR : '#1f1f1f',
    DATETIME_PICKER_HOVERING_BACKGROUND_COLOR : '#666666',
    DATETIME_PICKER_TEXT_COLOR : '#aaaaaa',
    DATETIME_PICKER_CALENDAR_IMAGE_URL : '/res/lia/triton/img/img_calender_gray.png',
    DATETIME_PICKER_CALENDAR_PRESSED_IMAGE_URL : '/res/lia/triton/img/img_calender_gray_pressed.png',
    // 변경 필요해 보임
    DATETIME_PICKER_DELETE_IMAGE_URL :'/res/lia/triton/img/img_file_delete.png',

    RADIO_BUTTON_NORMAL_IMAGE_URL : '/res/lia/triton/img/radiobtn.png',
    RADIO_BUTTON_PRESSED_IMAGE_URL : '/res/lia/triton/img/radiobtn_pressed.png',
    RADIO_BUTTON_INACTIVE_IMAGE_URL : '/res/lia/triton/img/radiobtn_inactive.png',

    PAGER_BACKGROUND_COLOR : '#1f1f1f',
    PAGER_PRESSED_BACKGROUND_COLOR : '#666666',
    PAGER_BORDER_COLOR : '#414141',
    PAGER_TEXT_COLOR : '#aaaaaa',
    PAGER_PRESSED_TEXT_COLOR : '#ffffff',
    // pressed 이미지 필요
    PAGER_ARROW_FIRST_IMAGE_URL : '/res/lia/triton/img/img_arrow_first.png',
    PAGER_ARROW_FIRST_PRESSED_IMAGE_URL : '/res/lia/triton/img/img_arrow_first_pressed.png',
    PAGER_ARROW_LAST_IMAGE_URL : '/res/lia/triton/img/img_arrow_last.png',
    PAGER_ARROW_LAST_PRESSED_IMAGE_URL : '/res/lia/triton/img/img_arrow_last_pressed.png',
    PAGER_ARROW_PREV_IMAGE_URL : '/res/lia/triton/img/img_arrow_prev.png',
    PAGER_ARROW_PREV_PRESSED_IMAGE_URL : '/res/lia/triton/img/img_arrow_prev_pressed.png',
    PAGER_ARROW_NEXT_IMAGE_URL : '/res/lia/triton/img/img_arrow_next.png',
    PAGER_ARROW_NEXT_PRESSED_IMAGE_URL : '/res/lia/triton/img/img_arrow_next_pressed.png',

    SEARCH_BACKGROUND_COLOR : '#1f1f1f',
    SEARCH_BORDER_COLOR : '#414141',
    SEARCH_TEXT_COLOR : '#aaaaaa',
    SEARCH_ARROW_COLOR : '#aaaaaa',
    SEARCH_ICON_IMAGE_URL : '/res/lia/triton/img/btn_search.png',
    SEARCH_CATEGORY_BACKGROUND_COLOR : '#1f1f1f',
    SEARCH_CATEGORY_BORDER_COLOR : '#414141',
    SEARCH_CATEGORY_TEXT_COLOR : '#aaaaaa',
    SEARCH_CATEGORY_ARROW_COLOR : '#aaaaaa',

    UPLOADER_BORDER_COLOR : '#414141',
    UPLOADER_BACKGROUND_COLOR : '#1f1f1f',
    UPLOADER_HOVERING_BACKGROUND_COLOR : '#666666',
    UPLOADER_TEXT_COLOR : '#aaaaaa',
    UPLOADER_HOVERING_TEXT_COLOR : '#ffffff',
    UPLOADER_FILE_ITEM_TEXT_COLOR : '#aaaaaa',
    UPLOADER_FILE_ICON_IMAGE_URL : '/res/lia/triton/img/img_file.png',
    UPLOADER_FILE_ITEM_DELETE_IMAGE_URL : '/res/lia/triton/img/img_file_delete.png',
    UPLOADER_FILE_ITEM_ICON_IMAGE_URL : '/res/lia/triton/img/img_file.png',
    UPLOADER_THUMBNAIL_ICON_IMAGE_URL : '/res/lia/triton/img/img_file_icon.png',
    UPLOADER_THUMBNAIL_DELETE_IMAGE_URL : '/res/lia/triton/img/img_small_x_red.png',

    TEXT_AREA_BACKGROUND_COLOR : '#1f1f1f',
    TEXT_AREA_TEXT_COLOR : '#aaaaaa',
    TEXT_AREA_BORDER_COLOR : '#414141',

    LOADING_IMAGE_URL : '/res/lia/triton/img/loading_bar_gray/img_{index}.png',
    LOADING_IMAGE_START_INDEX : 1,
    LOADING_IMAGE_END_INDEX : 8,

    init : function() {
        $('body').css({
            'background-color' :TritonTheme.BACKGROUND_COLOR,
            'color' :TritonTheme.TEXT_COLOR
        });
    }
};
